name: Scape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: |-
          curl -O "https://www.nyc.gov/assets/nypd/downloads/pdf/public_information/public-pguide[1-3].pdf"
          curl -O "https://www.nyc.gov/assets/nypd/downloads/pdf/public_information/public-adminguide[1-2].pdf"
      - name: Fetch update.pdf
        continue-on-error: true
        run: |-
          rm update.pdf Update.pdf Update1.pdf
          curl --fail -O https://www.nyc.gov/assets/nypd/downloads/pdf/public_information/update.pdf
          curl --fail -O https://www.nyc.gov/assets/nypd/downloads/pdf/public_information/Update.pdf
          curl --fail -O https://www.nyc.gov/assets/nypd/downloads/pdf/public_information/Update1.pdf
      - name: Validate update.pdf
        run: test -f update.pdf -o -f Update.pdf -o -f Update1.pdf
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest Patrol Guide: ${timestamp}" || exit 0
          git push
